version: "3.8"
services:
  frontend_server:
    # image: s0n9h2/react-pill-my-rhythm-app:1.0.0
    image: s0n9h2/react-pill-my-rhythm-app:1.0.5
    restart: "on-failure"
    volumes:
      - ./certbot/www:/etc/letsencrypt
      - ./front/nginx.conf:/etc/nginx/conf.d/nginx.conf
      #- ./certbot/www:/etc/letsencrypt
      #- ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443

  backend_server:
    image: tbr06057/node-pill-my-rhythm-app:1.0.4
    restart: "on-failure"
    ports:
      - 5000:5000

  redis_server:
    restart: "on-failure"
    image: redis:alpine
    container_name: "redis-app"

  ai_server:
    image: tbr06057/python-pill-my-rhythm-app:1.0.0
    restart: "on-failure"
    ports:
      - 5002:5002
